#!/bin/bash

# removing any previous build folder
if [ -d "build_release" ]; then
  rm -r "build_release"
fi

if [ -z $UPIPE_ROOT ]; then
  echo "UPIPE_ROOT is not defined"
  exit 1
fi

read -r -p "Are you sure you want to run the production release? [y/N] " response
if [[ "$response" =~ ^(yes|y)$ ]]; then
  qbs build_release project.releaseType:production qbs.installRoot:$UPIPE_ROOT
fi
