#!/bin/bash

# Environments/scripts that can only be defined/started after the
# versioned environments have been resolved. This file gets sourced
# automatically before the versioned scripts initialization to expand
# the auxiliary variables.

# uver versions directory
export UVER_VERSIONS_DIR=$(eval "echo $UVER_VERSIONS_DIR")

# ulauncher config directory
export ULAUNCHER_CONFIG_DIR=$(eval "echo $ULAUNCHER_CONFIG_DIR")
