#!/bin/bash

#          ,.,
#         UEVENTS_    ,..,
#           "_ "__"UVER          ,.......,,
#    ,..., __." --"    ,.,     _-"UFACILITY
#    "UCORE___ "_._   MMM"_."" _ """"""""""
#    """""    "" , \_.   "_. ."
#           ,., _"__ \__./ ."
#       ULAUNCHER_"  "_    ./
#           ''''      (    )
#    ._______________.-'____"---._.
#     \          UMEDIA          /
#      \________________________/
#      (_)                    (_)
#
# Should be called after ./env as a separated call inside of ~./bashrc. Therefore,
# letting users to be able to override locally any environment value that was previously
# set during ./env execution.

# auto-assigning UPIPE_PATH based on UPIPE_ROOT (when necessary)
if [ -z "$UPIPE_PATH" ]; then
  export UPIPE_PATH="$UPIPE_ROOT"
fi

# checking if it's being triggered under upipe domain
if [ -z "$UPIPE_ROOT" ]; then
  echo "UPIPE_ROOT IS NOT DEFINED, ARE YOU UNDER UPIPE ENV ?" >&2
elif [ -z "$UPIPE_PATH" ]; then
  echo "UPIPE_PATH IS NOT DEFINED, ARE YOU UNDER UPIPE ENV ?" >&2
else
  # current dir
  dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

  # development enviromnent support
  alias devenv='bash --init-file <(echo "export UPIPE_DEV_ROOT=$UPIPE_DEV_ROOT_TARGET && source $HOME/.bashrc")'
  if ! [[ -z "$UPIPE_DEV_ROOT" ]]; then
    PS1="[DEV]\t-\u@\h:\w\$ "
  fi

  # adding ubash bin path to the environment
  ubashBinPath+="$dir/bin"
  if ! [ "$UBASH_BIN_PATH" == "$ubashBinPath" ]; then
    export UBASH_BIN_PATH=$ubashBinPath
    export PATH="$UBASH_BIN_PATH:$PATH"
  fi

  # by default the version of versioned depedencies is driven by their
  # respective version environment. However when ubash is set to "stable", "beta" or
  # "alpha" this value can be used to drive the defaults of the versioned depedencies
  # that have not been defined yet. Also, if the target of versioned depedencies is a
  # symlink it is going to extract the target and assign to the version variable.
  # This is necessary to ensure the environment is going to be the same, no matter
  # what. Therefore, any changes in symlinks aka "stable" or "beta" is not going
  # to affect the current environment.
  versionedNames="UCORE UFACILITY UVER ULAUNCHER UEVENTS"
  autoAssignTypes="stable beta alpha"
  bashVersionType=$UBASH_VERSION
  for versioned in $versionedNames "UBASH";
  do
    versionedVersionName="${versioned}_VERSION"
    versionedVersionValue="${!versionedVersionName}"

    # when bash version is assigned with stable, beta, alpha and the versioned does not
    # have a value assigned to it.
    if [[ -z "$versionedVersionValue" && "$autoAssignTypes" == *"$bashVersionType"* ]]; then
      versionedVersionValue=$bashVersionType
    fi

    # showing an error when versioned is not defined at this point
    if [ -z "$versionedVersionValue" ]; then
      echo "ubash error: $versioned version is not defined (\$$versionedVersionName)!" >&2
      continue
    fi

    # we also want to resolve the version of ubash itself, but we don't need
    # to look for it
    if [[ "$versioned" == "UBASH" ]]; then
      versionedTarget="$dir"

    # looking for versioned targets
    else
      # looking for the versioned first under the upipe root (root repository), if it
      # is not there yet then try to find it using locres (in case it's a module that
      # is still under development)
      versionedTarget="$UPIPE_ROOT/${versioned~~}/$versionedVersionValue"

      if ! [[ -d "$versionedTarget" ]]; then
        # in case the module is not release yet under UPIPE_ROOT, make sure you
        # have the symlinks "alpha, beta and stable" for the dev module.
        versionedTarget="$( locres ${versioned~~}/$versionedVersionValue )"
      fi
    fi

    # additionally, if versioned target is a symlink, lets assign the target
    # rather than keeping a symlink that may change...
    # The target symlink can also be another symlink aka alpha pointing
    # to beta and beta pointing to stable, handling that behaviour
    for symlinkPointingTo in $autoAssignTypes;
    do
      if [[ -L "$versionedTarget" && -d "$versionedTarget" ]]; then
        versionedVersionValue=$(readlink "$versionedTarget")
        versionedVersionValue=$(basename "$versionedVersionValue")
      fi

      # when found version is not a symlink, stopping it
      versionedTarget="$(dirname $versionedTarget)/$versionedVersionValue"
      if ! [[ -L "$versionedTarget" && -d "$versionedTarget" ]]; then
        break
      fi
    done

    # exporting the final version of the versioned variable
    export "$versionedVersionName"=$versionedVersionValue
  done

  # running auxiliary envs after the versioned envs have been resolved and
  # before the initialization of the versioned scripts (since the scripts
  # may use them)
  source $dir/aux

  # running versioned initialization
  for versioned in $versionedNames
  do
    versionedVersionName="${versioned}_VERSION"
    versionedVersionValue="${!versionedVersionName}"

    # initializing versioned
    versionedLocation="$( locres ${versioned~~}/$versionedVersionValue )"
    if [ -d "$versionedLocation" ]; then

      # sourcing init file when necessary
      initFile="$versionedLocation/init"
      if [ -f "$initFile" ]; then
        source $versionedLocation/init
      fi

      # otherwise something went wrong...
    else
      echo "ubash error: $versioned could not be localized ($versionedLocation)!" >&2
    fi
  done
fi
